name: food_market
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.11+11

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  octo_image: ^2.0.0
  provider: ^6.0.5
  readmore: ^2.2.0
  screenshot: ^2.3.0
  shared_preferences: ^2.2.2
  smooth_star_rating_null_safety: ^1.0.4+2
  supercharged: ^2.1.1
  very_good_analysis: ^5.1.0
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
